UPBRASIL/Models/BDbase.cs
using Microsoft.EntityFrameworkCore;

namespace UPBRASIL.Models
{
    public class BDbase : DbContext
    {
        public DbSet<Produtos> Produtos { get; set; }   
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(connectionString: @"Server=DESKTOP-085RSKP\SQLEXPRESS;Database=UPBRASIL;integrated security=True");
        }
    }
}

UPBRASIL/Models/ErrorViewModel.cs
using System;

namespace UPBRASIL.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

UPBRASIL/Models/Produtos.cs
using System;

namespace UPBRASIL.Models
{
    public class Produtos
    {
        public int Id { get; set; }
        public string Name { get; set; }    
        public string Descricao { get; set; }
        public bool Ativo { get; set; }
        public DateTime Data { get; set; } 
    }
}

UPBRASIL/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using UPBRASIL.Models;

namespace UPBRASIL.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

UPBRASIL/Controllers/ProdutoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UPBRASIL.Models;

namespace UPBRASIL.Controllers
{
    public class ProdutoController : Controller
    {
        private readonly BDbase _context;

        public ProdutoController(BDbase context)
        {
            _context = context;
        }

        // GET: Produto
        public async Task<IActionResult> Index(string Pesquisa = "")
        {
            var q = _context.Produtos.AsQueryable();
            if (!string.IsNullOrEmpty(Pesquisa))
                q = q.Where(h => h.Name.Contains(Pesquisa));
            q = q.OrderBy(h => h.Name);
            return View(q.ToList());
        }


        ////GET: Produto/Pesquisa/5
        //public ActionResult Index(string Pesquisa = "")
        //{
        //    var q = _context.Produtos.AsQueryable();
        //    if (!string.IsNullOrEmpty(Pesquisa))
        //        q = q.Where(h => h.Name.Contains(Pesquisa));
        //    q = q.OrderBy(h => h.Name); 

        //    return View(q.ToList()) ;
        //}
      
        // GET: Produto/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produtos = await _context.Produtos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (produtos == null)
            {
                return NotFound();
            }

            return View(produtos);
        }

        // GET: Produto/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Produto/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Descricao,Ativo,Data")] Produtos produtos)
        {
            if (ModelState.IsValid)
            {
                _context.Add(produtos);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(produtos);
        }

        // GET: Produto/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produtos = await _context.Produtos.FindAsync(id);
            if (produtos == null)
            {
                return NotFound();
            }
            return View(produtos);
        }

        // POST: Produto/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Descricao,Ativo,Data")] Produtos produtos)
        {
            if (id != produtos.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(produtos);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProdutosExists(produtos.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(produtos);
        }

        // GET: Produto/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produtos = await _context.Produtos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (produtos == null)
            {
                return NotFound();
            }

            return View(produtos);
        }

        // POST: Produto/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var produtos = await _context.Produtos.FindAsync(id);
            _context.Produtos.Remove(produtos);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProdutosExists(int id)
        {
            return _context.Produtos.Any(e => e.Id == id);
        }
    }
}

UPBRASIL/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
<h1>---Bem vindo, Projeto CRUD para a UPBRASIL---</h1>    
<p>Este projeto tem como objetivo atender as seguintes demandas: 
Criação de uma pequena aplicação CRUD , qualquer versão do dotnet, preferencialmente web/c#, 
qualquer banco de dados relacional, sendo preferencialmente sql server p/ persistência dos dados.
</p>
<b>Cadastro de Produtos<br />
Codigo (pk) <br />
nome <br />
Descrição <br />
status ativo ( 0/1) Sim / Não <br />
Data de Cadastro<br />
<br /><br />
Tela de Pesquisa <br />
Edição <br />
Cadastro <br />
Exclusão <br />
</b>
------------------------------------------------------------------------------------------------------------<br />
A ideia inicial do projeto era fazer em webforms para não conflitar com o projeto do meu amigo ari,
porem o mesmo falou que faria em webforms. então pensei porque não aproveitar para aprender alguma coisa nova
resolvi fazer meu projeto com .net-core e ultilizando o scaffolding.
também foi usado 2 bibliotecas(NuGet) = <br />
-Microsoft.EntityFrameworkCore.SqlServer<br />
-Microsoft.EntityFrameworkCore.Tools<br />

<p>
Em relação ao banco aproveitei para entender como funciona melhor as migrations.

independente de qual quer coisa este projeto serviu para meu aprendizado pessoal. 
</p>
<b>(obrigado UPBRASIL pela oportunidade)</b>
<br />
<br />
<br />
<br />
<p><b>Instruções basicas estão no <a asp-action="Privacy">privacy</a></b></p>

</div>

UPBRASIL/Views/Produto/Create.cshtml
@model UPBRASIL.Models.Produtos

@{
    ViewData["Title"] = "Create";
}

<h4>Cadastra Produtos</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" required /> @*campo esta como obrigatorio*@
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Ativo" /> @Html.DisplayNameFor(model => model.Ativo)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Data" class="control-label"></label>
                <input asp-for="Data" class="form-control" />
                <span asp-validation-for="Data" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Cadastra" class="btn btn-primary" /> | 
                <a asp-action="Index" class="btn btn-info"><i class="fa fa-undo " aria-hidden="true"></i> Volta Para a lista</a>

            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

UPBRASIL/Views/Produto/Delete.cshtml
@model UPBRASIL.Models.Produtos

@{
    ViewData["Title"] = "Delete";
}


<h3>Realmente quer deleta?</h3>
<br />
<div>
    <h4>Produtos</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ativo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Data)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Data)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-info"><i class="fa fa-undo " aria-hidden="true"></i> Volta Para a lista</a>
    </form>
</div>

UPBRASIL/Views/Produto/Details.cshtml
@model UPBRASIL.Models.Produtos

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Produtos</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ativo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Data)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Data)
        </dd>
    </dl>
</div>
<div>                

    <a asp-action="Edit"  class="btn btn-primary" asp-route-id="@Model.Id">Edit</a> |
<a asp-action="Index" class="btn btn-info"><i class="fa fa-undo " aria-hidden="true"></i> Volta Para a lista</a>
</div>

UPBRASIL/Views/Produto/Edit.cshtml
@model UPBRASIL.Models.Produtos

@{
    ViewData["Title"] = "Edit";
}


<h4>Editar Produtos</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Ativo" /> @Html.DisplayNameFor(model => model.Ativo)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Data" class="control-label"></label>
                <input asp-for="Data" class="form-control" />
                <span asp-validation-for="Data" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />|<a asp-action="Index" class="btn btn-info"><i class="fa fa-undo " aria-hidden="true"></i> Volta Para a lista</a>

            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

UPBRASIL/Views/Produto/Index.cshtml
@model IEnumerable<UPBRASIL.Models.Produtos>

@{
    ViewData["Title"] = "Index";
}



<p class="btn btn-warning"  >
    <a asp-action="Create" style="text-decoration: none;">Cadastra Produto</a>
</p>
<p class="form-group">
    Pesquisar por Nome
    @using (Html.BeginForm("Index", "Produto", FormMethod.Get))
    {
        @Html.TextBox("Pesquisa")
        <input  class="form-group" type="submit" value="Pesquisar" />        
    }

</p>
    <div id="table-wrapper">
  <div id="table-scroll">  
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descricao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ativo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Data)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descricao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ativo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Data)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="fa fa-pencil-square-o" aria-hidden="true"></a> |
                <a asp-action="Details" asp-route-id="@item.Id" class="fa fa-search-plus" aria-hidden="true"></a> |
                <a asp-action="Delete" asp-route-id="@item.Id" class="fa fa-trash" aria-hidden="true"></a>
            </td>
        </tr>
}
    </tbody>
</table>
<div>

</div>

UPBRASIL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UPBRASIL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/font-awesome-4.7.0/css/font-awesome.css" />


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">UPBRASIL</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produto" asp-action="Index">Produto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - UPBRASIL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>